{% set version = "0.0.17" %}

package:
  name: pwabuilder-cli
  version: {{ version }}

source:
  url: https://registry.npmjs.org/@pwabuilder/cli/-/cli-{{ version }}.tgz
  sha256: 3c24e3d086ab0c5f27defa0c0209f84e7b36da6878ccda0d600aa28eb8abb237

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - make
    - nodejs
    - pnpm
    - pnpm-licenses
  host:
    - nodejs
  run:
    - nodejs

test:
  commands:
    - pwa --help

about:
  license: MIT
  license_file:
    - LICENSE.txt
    - third-party-licenses.txt
  summary: The simplest way to create progressive web apps across platforms and devices.
  home: https://pwabuilder.com
  dev_url: https://github.com/pwa-builder/PWABuilder

extra:
  recipe-maintainers:
    - danielnachun
